name: Demoblaze E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false  # Don't cancel other browsers if one fails
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Smoke Tests
      run: npx playwright test tests/demoblaze/ --grep="@smoke" --project=${{ matrix.browser }}
      env:
        BASE_URL: https://www.demoblaze.com
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-results-${{ matrix.browser }}
        path: |
          test-results/
          playwright-report/
        retention-days: 30

  regression-tests:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    needs: smoke-tests
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Regression Tests
      run: npx playwright test --grep="@regression" --retries=2
      env:
        BASE_URL: https://www.demoblaze.com
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regression-results
        path: |
          test-results/
          playwright-report/
        retention-days: 30